version: '3.7'

services:
  redis:
    image: redis:5.0.5-alpine
    networks:
      - default

  webapp:
    build: .
    command: /app/bin/webapp
    environment:
      - RACK_ENV=production
      - REDIS_URL=redis://redis:6379
    ports:
      - 4567:4567
    networks:
      - default

  workers:
    build: .
    command: /app/bin/workers
    environment:
      - RACK_ENV=production
      - REDIS_URL=redis://redis:6379
    networks:
      - default

networks:
  default:
volumes:
  card-parsers-db-data:
